"""add kb upload unique constraint and updated_at

Revision ID: 8cd951190b78
Revises: 8ec36703fa78
Create Date: 2026-04-23 18:32:38.845949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd951190b78'
down_revision: Union[str, Sequence[str], None] = '8ec36703fa78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 给空 hash 的历史记录填唯一占位，避免去重时误合并不同文件。
    op.execute("""
        UPDATE knowledge_documents
        SET file_hash = 'legacy-' || id
        WHERE file_hash = '' OR file_hash IS NULL
    """)

    # 去重：优先保留 completed 记录，同状态下保留 id 最大的；
    # 避免旧逻辑产生的重复数据阻塞唯一约束创建。
    op.execute("""
        DELETE FROM knowledge_documents
        WHERE id NOT IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY collection_name, file_hash
                    ORDER BY
                        CASE status WHEN 'completed' THEN 0 ELSE 1 END,
                        id DESC
                ) AS rn
                FROM knowledge_documents
            )
            WHERE rn = 1
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_kb_collection_hash', ['collection_name', 'file_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_kb_collection_hash', type_='unique')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
