"""add knowledge document fields

Revision ID: 8ec36703fa78
Revises: 97eaf6c6be6f
Create Date: 2026-04-22 14:03:59.776865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec36703fa78'
down_revision: Union[str, Sequence[str], None] = '97eaf6c6be6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 给新增非空列补 server_default，旧 SQLite 行升级时才能顺利回填。
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('filename', sa.String(length=255), nullable=False, server_default='unknown'))
    op.add_column('knowledge_documents', sa.Column('collection_name', sa.String(length=100), nullable=False, server_default='default'))
    op.add_column('knowledge_documents', sa.Column('file_path', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('knowledge_documents', sa.Column('file_hash', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('knowledge_documents', sa.Column('chunks_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('knowledge_documents', sa.Column('status', sa.String(length=20), nullable=False, server_default='completed'))
    op.add_column('knowledge_documents', sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'file_size')
    op.drop_column('knowledge_documents', 'status')
    op.drop_column('knowledge_documents', 'chunks_count')
    op.drop_column('knowledge_documents', 'file_hash')
    op.drop_column('knowledge_documents', 'file_path')
    op.drop_column('knowledge_documents', 'collection_name')
    op.drop_column('knowledge_documents', 'filename')
    # ### end Alembic commands ###
