"""expand_resume_records_fields

Revision ID: 9f04e319acd4
Revises: f8f3a6c2d1b4
Create Date: 2026-05-13 00:53:05.643472

"""
import hashlib
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column


# revision identifiers, used by Alembic.
revision: str = '9f04e319acd4'
down_revision: Union[str, Sequence[str], None] = 'f8f3a6c2d1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('target_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('analysis_result', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('raw_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    resume_records = table(
        'resume_records',
        column('id', sa.Integer()),
        column('filename', sa.String(length=255)),
        column('content_hash', sa.String(length=64)),
        column('status', sa.String(length=20)),
    )
    op.execute(
        resume_records.update()
        .where(resume_records.c.filename.is_(None))
        .values(filename='legacy_resume')
    )
    connection = op.get_bind()
    rows = connection.execute(
        sa.select(resume_records.c.id).where(resume_records.c.content_hash.is_(None))
    )
    for row in rows:
        legacy_hash = hashlib.sha256(f'legacy-resume-record:{row.id}'.encode()).hexdigest()
        connection.execute(
            resume_records.update()
            .where(resume_records.c.id == row.id)
            .values(content_hash=legacy_hash)
        )
    op.execute(
        resume_records.update()
        .where(resume_records.c.status.is_(None))
        .values(status='pending')
    )

    with op.batch_alter_table('resume_records', schema=None) as batch_op:
        batch_op.alter_column('filename', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('content_hash', existing_type=sa.String(length=64), nullable=False)
        batch_op.alter_column('status', existing_type=sa.String(length=20), nullable=False)
        batch_op.create_index(batch_op.f('ix_resume_records_content_hash'), ['content_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_records_content_hash'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('raw_text')
        batch_op.drop_column('analysis_result')
        batch_op.drop_column('target_role')
        batch_op.drop_column('status')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
